# mendefinisikan versi skema
version: '3.8'

# mendefinisikan servis-servis
services:
  # mendefinisikan servis item-app
  item-app:
    # mendefinisikan base iamge untuk item app
    image: faishalshidqi/item-app:v1
    # mendefinisikan port mapping untuk item app
    ports:
      - "80:8080"
    # memastikan item-app berjalan setelah item-db tuntas
    depends_on:
      - item-db
    # mendefinisikan restart policy
    restart: always

  # mendefinisikan servis item-db
  item-db:
    # mendefinisikan base image untuk item-db
    image: mongo:3
    # mendefinisikan restart policy
    restart: always
    # mendefinisikan volumes yang digunakan oleh item-db
    volumes:
      - app-db:/data/db

# mendefinisikan volumes yang akan digunakan oleh item-db
volumes:
  app-db:
