version: "3.2"

services:
  rabbitmq:
    image: rabbitmq:3.11-management
    container_name: 'rabbitmq_container'
    ports:
      - "5673:5672"
      - "15673:15672"
    volumes:
      - ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq
      - ~/.docker-conf/rabbitmq/log/:/var/log/rabbitmq
    networks:
      - rabbitmq_network
  order-service:
    image: faishalshidqi/order-service:latest
    build:
      context: ./
      target: dev
    ports:
      - "3000:3000"
    volumes:
      - .:/src
    depends_on:
      - "rabbitmq"
    command: sh -c '/bin/wait-for-it.sh rabbitmq:5672 --timeout=30 -- node index.js'
    environment:
      PORT: 3000
      NODE_ENV: production
      AMQP_URL: amqp://guest:guest@rabbitmq:5672
    networks:
      - rabbitmq_network
  shipping-service:
    image: faishalshidqi/shipping-service:latest
    build:
      context: ../shipping-service-submission-microservices
      target: dev
    depends_on:
      - "rabbitmq"
    command: sh -c '/bin/wait-for-it.sh rabbitmq:5672 --timeout=30 -- node index.js'
    environment:
      PORT: 3001
      NODE_ENV: production
      AMQP_URL: amqp://guest:guest@rabbitmq:5672
    networks:
      - rabbitmq_network
networks:
  rabbitmq_network:
    driver: bridge
